spring:
  application:
    name: NeoNHS
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 16079
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false
      timeout: 60000
  mongodb:
    uri: ${MONGO_URI}
    database: ${MONGO_DATABASE}
  mail:
    username: phamminhkiet24@gmail.com
    password: ${GOOGLE_MAIL_PASSWORD}

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yand0c2lnbmluZ3B1cnBvc2Vz
    expiration-ms: 86400000 # 24 hours
  fe-url: http://localhost:3000
  fe-url-setpassword: ${FE_URL:http://localhost:8080}

google-auth:
  client-id: ${GOOGLE_AUTH_CLIENT_ID}
  client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}

# VNPT eKYC Configuration
vnpt:
  ekyc:
    access-token: ${VNPT_EKYC_ACCESS_TOKEN}
    token-id: ${VNPT_EKYC_TOKEN_ID}
    token-key: ${VNPT_EKYC_TOKEN_KEY}

# NeoNHS Face Verification Service (Python microservice)
face-service:
  base-url: ${FACE_SERVICE_URL:https://huydoan961-neonhs-face-service.hf.space}

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

#github token
github:
  token: ${GITHUB_TOKEN}