---
config:
  theme: base
  themeVariables:
    primaryColor: "#ffffff"
    primaryTextColor: "#000000"
    primaryBorderColor: "#000000"
    activationBkgColor: "#eeeeee"
    activationBorderColor: "#000000"
    actorBkg: "#ffffff"
    actorTextColor: "#000000"
    actorBorder: "#000000"
    altBackground: "#f5f5f5"
    altBorder: "#000000"
  sequence:
    actorMargin: 10
    messageMargin: 0
---
sequenceDiagram
    actor Tourist as Tourist <br/> <<user>>
    participant PointDetailPage as PointDetailPage <br/> <<user interaction>>
    participant PointController as PointController <br/> <<controller>>
    participant PointService as PointService <br/> <<service>>
    participant PointRepository as PointRepository <br/> <<repository>>
    participant DB

    Tourist->>+PointDetailPage: 1. Request direction to point
    PointDetailPage->>+PointController: 2. getPointById(pointId)
    PointController->>+PointService: 3. getPointById(pointId)
    PointService->>+PointRepository: 4. findById(pointId)
    PointRepository->>+DB: 5. findById(pointId)
    DB-->>-PointRepository: 6. Point entity
    PointRepository-->>-PointService: 7. Point entity

    alt 8A Point not found or is deleted
        PointService-->>PointController: 8A1. Exception: Point not found
        PointController-->>PointDetailPage: 8A2. Error response
        PointDetailPage-->>Tourist: 8A3. Show error message
    else 8B Point found
        PointService->>PointService: 8B1. mapToResponse(point)
        PointService-->>-PointController: 8B2. PointResponse
        PointController-->>-PointDetailPage: 8B3. PointResponse
        Note right of PointDetailPage: App use Google Map library <br/> for directions
        PointDetailPage->>PointDetailPage: 8B4. getGoogleMapDirections()
        PointDetailPage-->>-Tourist: 8B5. Show direction to User
    end