---
config:
  theme: base
  themeVariables:
    primaryColor: "#ffffff"
    primaryTextColor: "#000000"
    primaryBorderColor: "#000000"
    activationBkgColor: "#eeeeee"
    activationBorderColor: "#000000"
    actorBkg: "#ffffff"
    actorTextColor: "#000000"
    actorBorder: "#000000"
    altBackground: "#f5f5f5"
    altBorder: "#000000"
  sequence:
    actorMargin: 0
    messageMargin: 5
---
sequenceDiagram
    actor Admin as Admin <br/> <<user>>
    participant AdminScreen as AdminScreen <br/> <<user interaction>>
    participant AdminBlogCategoryController as AdminBlogCategoryController <br/> <<controller>>
    participant BlogCategoryService as BlogCategoryService <br/> <<service>>
    participant BlogCategoryRepository as BlogCategoryRepository <br/> <<repository>>
    participant DB

    Admin->>+AdminScreen: 1. Click delete category
    AdminScreen->>+AdminBlogCategoryController: 2. deleteCategory(categoryId)
    AdminBlogCategoryController->>+BlogCategoryService: 3. deleteCategory(categoryId)
    
    BlogCategoryService->>+BlogCategoryRepository: 4. findById(categoryId)
    BlogCategoryRepository->>+DB: 5. findById(categoryId)
    DB-->>-BlogCategoryRepository: 6. Category result
    BlogCategoryRepository-->>-BlogCategoryService: 7. Category result
    
    %% Validation
    alt 8A Category not found
        BlogCategoryService-->>AdminBlogCategoryController: 8A1. Category not found
        AdminBlogCategoryController-->>AdminScreen: 8A2. Error response
        AdminScreen-->>Admin: 8A3. Show error
    else 8B Category link to existing blog
        BlogCategoryService-->>AdminBlogCategoryController: 8B1. Category link to existing blog <br/> cannot delete
        AdminBlogCategoryController-->>AdminScreen: 8B2. Error response
        AdminScreen-->>Admin: 8B3. Show cant delete error
    else 8C Category link to no blog
        BlogCategoryService->>+BlogCategoryRepository: 8C1. delete(category)
        BlogCategoryRepository->>+DB: 8C2. delete(category)
        DB-->>-BlogCategoryRepository: 8C3. Deleted Entity
        BlogCategoryRepository-->>-BlogCategoryService: 8C4. Deleted Entity
    end
    BlogCategoryService-->>-AdminBlogCategoryController: 9. Category deleted successfully
    AdminBlogCategoryController-->>-AdminScreen: 10. Category deleted successfully
    AdminScreen-->>-Admin: 11. Show success message
