---
config:
  theme: base
  themeVariables:
    primaryColor: "#ffffff"
    primaryTextColor: "#000000"
    primaryBorderColor: "#000000"
    activationBkgColor: "#eeeeee"
    activationBorderColor: "#000000"
    actorBkg: "#ffffff"
    actorTextColor: "#000000"
    actorBorder: "#000000"
    altBackground: "#f5f5f5"
    altBorder: "#000000"
  sequence:
    actorMargin: 0
    messageMargin: 5
---
sequenceDiagram
    actor Admin as Admin <br/> <<user>>
    participant AdminScreen as AdminScreen <br/> <<user interaction>>
    participant AdminBlogController as AdminBlogController <br/> <<controller>>
    participant BlogService as BlogService <br/> <<service>>
    participant BlogRepository as BlogRepository <br/> <<repository>>
    participant DB

    Admin->>+AdminScreen: 1. Admin views blogs
    AdminScreen->>+AdminBlogController: 2. getBlogs(filter, page, size)
    AdminBlogController->>+BlogService: 3. getBlogs(filter, page, size)
    
    BlogService->>+BlogRepository: 4. findAll(filter, pageable)
    BlogRepository->>+DB: 5. findAll(filter, pageable)
    DB-->>-BlogRepository: 6. List of filtered blogs
    BlogRepository-->>-BlogService: 7. List of filtered blogs
    
    %% Validation
    alt 8A No blogs found
        BlogService-->>AdminBlogController: 8A1. No blogs found
        AdminBlogController-->>AdminScreen: 8A2. No blogs found, please try again later
        AdminScreen-->>Admin: 8A3. Show No blogs found error
    else 8B Blogs found
        BlogService->>BlogService: 8B1. Map to Response
    end
    BlogService-->>-AdminBlogController: 9. List of BlogResponse
    AdminBlogController-->>-AdminScreen: 10. List of blogs
    AdminScreen-->>-Admin: 11. Show blogs list

