---
config:
  theme: base
  themeVariables:
    primaryColor: "#ffffff"
    primaryTextColor: "#000000"
    primaryBorderColor: "#000000"
    activationBkgColor: "#eeeeee"
    activationBorderColor: "#000000"
    actorBkg: "#ffffff"
    actorTextColor: "#000000"
    actorBorder: "#000000"
    altBackground: "#f5f5f5"
    altBorder: "#000000"
  sequence:
    actorMargin: 0
    messageMargin: 5
---
sequenceDiagram
    actor Admin as Admin <br/> <<user>>
    participant AdminScreen as AdminScreen <br/> <<user interaction>>
    participant AdminBlogCategoryController as AdminBlogCategoryController <br/> <<controller>>
    participant BlogCategoryService as BlogCategoryService <br/> <<service>>
    participant BlogCategoryRepository as BlogCategoryRepository <br/> <<repository>>
    participant DB

    Admin->>+AdminScreen: 1. Input update category details
    AdminScreen->>+AdminBlogCategoryController: 2. updateCategory(categoryId, categoryRequest)
    AdminBlogCategoryController->>+BlogCategoryService: 3. updateCategory(categoryId, categoryRequest)
    
    %% Common Validation Box
    alt 4A Validation Failed
        BlogCategoryService-->>AdminBlogCategoryController: 4A1. Exception (Invalid Data)
        AdminBlogCategoryController-->>AdminScreen: 4A2. Invalid Data, please try again later
        AdminScreen-->>Admin: 4A3. Show Invalid Data error
    else 4B Validation Passed
        BlogCategoryService->>+BlogCategoryRepository: 4B1. findById(categoryId)
        BlogCategoryRepository->>+DB: 4B2. findById(categoryId)
        DB-->>-BlogCategoryRepository: 4B3. Category result
        BlogCategoryRepository-->>-BlogCategoryService: 4B4. Category result
        
        alt 5A Category not found
            BlogCategoryService-->>AdminBlogCategoryController: 5A1. Exception (Not Found)
            AdminBlogCategoryController-->>AdminScreen: 5A2. Category not found, please try again later
            AdminScreen-->>Admin: 5A3. Show Category not found error
        else 5B Category name not unique
            BlogCategoryService-->>AdminBlogCategoryController: 5B1. Exception (Name Exists)
            AdminBlogCategoryController-->>AdminScreen: 5B2. Category name not unique, please try again later
            AdminScreen-->>Admin: 5B3. Show name exists error
        else 5C Category name unique
            BlogCategoryService->>BlogCategoryService: 5C1. Update Entity fields
            BlogCategoryService->>+BlogCategoryRepository: 5C2. save(category)
            BlogCategoryRepository->>+DB: 5C3. save(category)
            DB-->>-BlogCategoryRepository: 5C4. Saved Entity
            BlogCategoryRepository-->>-BlogCategoryService: 5C5. Saved Entity
        end
    end
    BlogCategoryService->>BlogCategoryService: 6. Map to Response
    BlogCategoryService-->>-AdminBlogCategoryController: 7. CategoryResponse
    AdminBlogCategoryController-->>-AdminScreen: 8. Category updated
    AdminScreen-->>-Admin: 9. Show category updated message
